DROP DATABASE IF  EXISTS HospitalManagementSystem
GO
CREATE DATABASE HospitalManagementSystem
GO
USE HospitalManagementSystem
GO
DROP TABLE IF EXISTS Hostpital
GO
CREATE TABLE  Place(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	City VARCHAR(255),
	PostalCode int NOT NULL
);
GO
DROP TABLE IF EXISTS Hostpital
GO
-- TODO FUNCTION/PROCEDUR to count employees
CREATE TABLE Hostpital(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	NameOfHostpital varchar(255)NOT NULL,
	Fk_Place int FOREIGN KEY REFERENCES  Place(Id) NOT NULL

);

GO
DROP TABLE IF EXISTS Person
GO
CREATE TABLE Person(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	LastName VARCHAR(255) NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	Birthday  DATETIME
);

GO
DROP TABLE IF EXISTS Disease
GO
CREATE TABLE Disease(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Desig VARCHAR(255) NOT NULL,
	isHealable  BIT NOT NULL
);
GO

DROP TABLE IF EXISTS Employee
GO
CREATE TABLE Employee(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	JobTitle VARCHAR(255) NOT NULL,
	HealthSector VARCHAR(255),
	EntryDate DATETIME NOT NULL,
	Fk_Person int FOREIGN KEY REFERENCES  Person(Id) NOT NULL,
	Fk_WorkingHostpital int FOREIGN KEY REFERENCES  Hostpital(Id) NOT NULL
	CONSTRAINT employeeIsUniqueForEeachHospital UNIQUE (Fk_Person,Fk_WorkingHostpital)

);
GO
DROP TABLE IF EXISTS Patient
GO
CREATE TABLE Patient(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Fk_Person int FOREIGN  KEY REFERENCES  Person(Id) NOT NULL,
	Fk_Stationed int FOREIGN  KEY REFERENCES  Hostpital(Id) NOT NULL,
	Fk_Disease int FOREIGN KEY REFERENCES  Disease(Id) NOT NULL,
	Fk_ResponsibleEmployee int FOREIGN KEY REFERENCES  Employee(Id) NOT NULL
);
GO

DROP TABLE IF EXISTS Medicine
Go
-- Desig stands for Designation
CREATE TABLE Medicine(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Desig VARCHAR(255) NOT NULL,
	Price DECIMAL (9,2) NOT NULL,
	Producer VARCHAR(255),
	CONSTRAINT DesigIsUniqueForEeachProducer UNIQUE (Desig,Producer)

);

GO
DROP TABLE IF EXISTS Supplier
Go
CREATE TABLE Supplier(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CompanyName VARCHAR(100),
	fk_Contact INT FOREIGN KEY REFERENCES Person(Id),
	CONSTRAINT companyNameIsUnique UNIQUE (CompanyName)

);
GO
DROP TABLE IF EXISTS SupplierDelivers
Go
CREATE TABLE SupplierDelivers(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	UnitsInStock INT,
	UnitsOnOrder INT,
	fk_Supplier INT FOREIGN KEY REFERENCES Supplier(Id) NOT NULL,
	fk_Medication INT FOREIGN KEY REFERENCES Medicine(Id),
	fk_Hospital INT FOREIGN KEY REFERENCES Medicine(Id) NOT NULL
);

CREATE TABLE DiseaseHistory(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	isHealed  BIT NOT NULL,
	EntryDate DATETIME NOT NULL,
	Discharge DATETIME,
	Fk_Hostpital INT FOREIGN KEY REFERENCES Hostpital (Id) NOT NULL,
	Fk_Patient INT FOREIGN KEY REFERENCES Patient(Id) NOT NULL,
	Fk_Employee INT FOREIGN KEY REFERENCES Employee(Id) NOT NULL,
	Fk_Medicine INT FOREIGN KEY REFERENCES Medicine(Id),
);

GO